name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          sudo apt update && sudo apt install -y curl

      - name: Run a Custom Task - 23f2003680@ds.study.iitm.ac.in
        run: echo "This step is executed by 23f2003680@ds.study.iitm.ac.in"

      - name: Run Tests
        run: |
          echo "Running tests..."
          echo "All tests passed successfully!"
